//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend_app
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AirsquireChallengeDBEntities : DbContext
    {
        public AirsquireChallengeDBEntities()
            : base("name=AirsquireChallengeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Config> Configs { get; set; }
        public virtual DbSet<PanoramaBookmark> PanoramaBookmarks { get; set; }
        public virtual DbSet<Panorama> Panoramas { get; set; }
    }
}
