//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class Panorama
    {
        public int Id { get; set; }
        public string ImageTitle { get; set; }
        public string ImageFilename { get; set; }
        public string UploadedBy { get; set; }
        public Nullable<System.DateTime> UploadedDate { get; set; }
    
        public virtual PanoramaBookmark PanoramaBookmark { get; set; }
    }
}
